# Generated by Django 3.2.2 on 2022-01-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0005_advertis_categorys'),
        ('app_category', '0002_rename_appcategory_advertiscategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdvertisCategory',
            new_name='AppCategory',
        ),
    ]
