# Generated by Django 3.2.2 on 2022-01-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='advertis',
        ),
    ]
