# Generated by Django 3.2.2 on 2021-12-31 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakhsh',
            name='ostan',
        ),
        migrations.RemoveField(
            model_name='bakhsh',
            name='shahrestan',
        ),
        migrations.RemoveField(
            model_name='dehestan',
            name='bakhsh',
        ),
        migrations.RemoveField(
            model_name='dehestan',
            name='ostan',
        ),
        migrations.RemoveField(
            model_name='dehestan',
            name='shahrestan',
        ),
        migrations.RemoveField(
            model_name='shahr',
            name='bakhsh',
        ),
        migrations.RemoveField(
            model_name='shahr',
            name='ostan',
        ),
        migrations.RemoveField(
            model_name='shahr',
            name='shahrestan',
        ),
        migrations.RemoveField(
            model_name='shahrestan',
            name='ostan',
        ),
        migrations.DeleteModel(
            name='Abadi',
        ),
        migrations.DeleteModel(
            name='Bakhsh',
        ),
        migrations.DeleteModel(
            name='Dehestan',
        ),
        migrations.DeleteModel(
            name='Ostan',
        ),
        migrations.DeleteModel(
            name='Shahr',
        ),
        migrations.DeleteModel(
            name='Shahrestan',
        ),
    ]
