# Generated by Django 3.2.2 on 2021-12-31 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Advertis',
        ),
    ]
