# Generated by Django 3.2.2 on 2021-12-31 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0002_rename_product_advertis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertis',
            options={'verbose_name': 'اگهی', 'verbose_name_plural': 'اگهی ها'},
        ),
    ]
