# Generated by Django 3.2.2 on 2022-01-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0003_alter_advertis_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertis',
            name='active',
            field=models.BooleanField(default=False, verbose_name='وجود دارد  / حذف شده'),
        ),
    ]
