# Generated by Django 3.2.2 on 2022-01-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_category', '0001_initial'),
        ('app_adv', '0004_alter_advertis_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertis',
            name='categorys',
            field=models.ManyToManyField(blank=True, to='app_category.AppCategory', verbose_name='دسته بندی ها'),
        ),
    ]
