# Generated by Django 3.2.2 on 2022-01-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0005_advertis_categorys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertis',
            old_name='categorys',
            new_name='categories',
        ),
    ]
