# Generated by Django 3.2.2 on 2022-02-14 20:38

import app_adv.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0008_auto_20220215_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='addadvertis',
            name='advertis',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app_adv.advertis', verbose_name='محصول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addadvertis',
            name='image',
            field=models.ImageField(default=2, upload_to=app_adv.models.upload_gallery_image_path, verbose_name='تصویر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addadvertis',
            name='location',
            field=models.CharField(default=2, max_length=20, verbose_name='موقعیت'),
            preserve_default=False,
        ),
    ]
