# Generated by Django 3.2.2 on 2022-02-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0009_auto_20220215_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addadvertis',
            name='categories',
        ),
    ]
