# Generated by Django 3.2.2 on 2022-02-15 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0011_auto_20220215_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addadvertis',
            old_name='Phone_Number',
            new_name='phone_number',
        ),
    ]
