# Generated by Django 3.2.2 on 2022-02-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0012_rename_phone_number_addadvertis_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addadvertis',
            name='image',
            field=models.ImageField(default=2, max_length=20, upload_to='', verbose_name='عکس'),
            preserve_default=False,
        ),
    ]
