# Generated by Django 3.2.2 on 2022-02-15 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0017_addadvertis_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addadvertis',
            old_name='image',
            new_name='images',
        ),
    ]
