# Generated by Django 3.2.2 on 2022-02-15 20:10

import app_adv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0018_rename_image_addadvertis_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addadvertis',
            name='images',
        ),
        migrations.AddField(
            model_name='addadvertis',
            name='image',
            field=models.ImageField(blank=True, max_length=20, null=True, upload_to=app_adv.models.upload_image_path, verbose_name='تصویر'),
        ),
    ]
