# Generated by Django 3.2.2 on 2022-02-15 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0020_alter_addadvertis_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addadvertis',
            name='image',
        ),
    ]
