# Generated by Django 3.2.2 on 2022-02-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0022_addadvertis_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addadvertis',
            options={'verbose_name': 'ثبت آگهی', 'verbose_name_plural': 'اگهی های ثبت شده '},
        ),
        migrations.AlterModelTable(
            name='addadvertis',
            table=None,
        ),
    ]
