# Generated by Django 3.2.2 on 2022-02-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0023_auto_20220217_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='addadvertis',
            name='price',
            field=models.IntegerField(default=2, verbose_name='قیمت'),
            preserve_default=False,
        ),
    ]
