# Generated by Django 3.2.2 on 2022-02-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0030_remove_advertis_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertis',
            name='image',
            field=models.ImageField(blank=True, max_length=20, null=True, upload_to='', verbose_name='عکس'),
        ),
    ]
