# Generated by Django 3.2.2 on 2022-02-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adv', '0035_alter_advertis_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertis',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/', verbose_name='تصویر'),
        ),
    ]
