# Generated by Django 3.2.2 on 2022-02-19 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_category', '0003_rename_advertiscategory_appcategory'),
        ('app_adv', '0039_auto_20220218_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertis',
            name='categories',
        ),
        migrations.AddField(
            model_name='advertis',
            name='categories',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app_category.appcategory', verbose_name='دسته بندی ها'),
            preserve_default=False,
        ),
    ]
