"""
Django settings for divar project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l1gq$bd#zsshqmd9lato2=5042x5p0q(pfcp)#vxr6rk!w-gkh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_render_partial',
    'app_account',
    'app_dashboard',
    'app_adv',
    'app_tag',
    'app_category',
    'location_field.apps.DefaultConfig',
    'phone_field',
    'app_sliders',
    'phonenumber_field',
    # 'app_phone',
    # 'iranian_cities',
    # 'cities',
    # 'django.contrib.gis.db.backends.postgis',
    # 'django.contrib.gis',
    # 'mapwidgets',
    # 'GDAL_LIBRARY_PATH'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'divar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',

            ],
        },
    },
]

WSGI_APPLICATION = 'divar.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOCATION_FIELD = {
    'provider.openstreetmap.max_zoom': 18,
}
# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "assets")
]
STATIC_ROOT = os.path.join(BASE_DIR, "static_cdn", "static_root")

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# LOCATION_FIELD_PATH = setting.STATIC_URL + 'location_field'
# LOCATION_FIELD = {
# 'map.provider': 'google',
# 'map.zoom': 13,
# 'search.provider': 'google',
# 'search.suffix': '',
# # Google
# 'provider.google.api': '//maps.google.com/maps/api/js?sensor=false',
# 'provider.google.api_key': '',
# 'provider.google.api_libraries': '',
# 'provider.google.map.type': 'ROADMAP',
# # Mapbox
# 'provider.mapbox.access_token': '',
# 'provider.mapbox.max_zoom': 18,
# 'provider.mapbox.id': 'mapbox.streets',
# # OpenStreetMap
# 'provider.openstreetmap.max_zoom': 18,
# # misc
# 'resources.root_path': LOCATION_FIELD_PATH,
# 'resources.media': {
# 'js': (
# LOCATION_FIELD_PATH + '/js/jquery.livequery.js',
# LOCATION_FIELD_PATH + '/js/form.js',
# ),
# },
# }


CITIES_VALIDATE_POSTAL_CODES = True
CITIES_LOCALES = ['en', 'und', 'LANGUAGES', 'ira', 'pes']
CITIES_POSTAL_CODES = ['ALL']

CITIES_FILES = {
    # ...
    'city': {
        'filename': 'cities1000.zip',
        'urls': ['http://download.geonames.org/export/dump/' + '{filename}']
    },
    # ...
}

#
# GOOGLE_MAP_API_KEY = "Create a google_map_api_key_and_past_it_here"

# MAP_WIDGETS = {
#     "GOOGLE_MAP_API_KEY": "Create a google_map_api_key_and_past_it_here"
# }
